# MediaPipe landmark indices
LANDMARKS = {
    "NOSE": 0,
    "LEFT_SHOULDER": 11,
    "RIGHT_SHOULDER": 12,
    "LEFT_ELBOW": 13,
    "RIGHT_ELBOW": 14,
    "LEFT_WRIST": 15,
    "RIGHT_WRIST": 16,
    "LEFT_HIP": 23,
    "RIGHT_HIP": 24,
    "LEFT_KNEE": 25,
    "RIGHT_KNEE": 26,
    "LEFT_ANKLE": 27,
    "RIGHT_ANKLE": 28,
}

# Lift-specific joints
LIFT_LANDMARKS = {
    "squat": [
        LANDMARKS["LEFT_SHOULDER"], LANDMARKS["RIGHT_SHOULDER"],
        LANDMARKS["LEFT_HIP"], LANDMARKS["RIGHT_HIP"],
        LANDMARKS["LEFT_KNEE"], LANDMARKS["RIGHT_KNEE"]
    ],
    "bench": [
        LANDMARKS["LEFT_SHOULDER"], LANDMARKS["RIGHT_SHOULDER"],
        LANDMARKS["LEFT_ELBOW"], LANDMARKS["RIGHT_ELBOW"],
        LANDMARKS["LEFT_WRIST"], LANDMARKS["RIGHT_WRIST"]
    ],
    "deadlift": [
        LANDMARKS["LEFT_SHOULDER"], LANDMARKS["RIGHT_SHOULDER"],
        LANDMARKS["LEFT_HIP"], LANDMARKS["RIGHT_HIP"],
        LANDMARKS["LEFT_KNEE"], LANDMARKS["RIGHT_KNEE"],
        LANDMARKS["LEFT_ANKLE"], LANDMARKS["RIGHT_ANKLE"]
    ]
}
